# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calculator_pb2 as calculator__pb2


class CalculatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sum = channel.unary_unary(
        '/Calculator/sum',
        request_serializer=calculator__pb2.Numbers.SerializeToString,
        response_deserializer=calculator__pb2.RNumber.FromString,
        )
    self.mult = channel.unary_unary(
        '/Calculator/mult',
        request_serializer=calculator__pb2.Numbers.SerializeToString,
        response_deserializer=calculator__pb2.RNumber.FromString,
        )
    self.div = channel.unary_unary(
        '/Calculator/div',
        request_serializer=calculator__pb2.Numbers.SerializeToString,
        response_deserializer=calculator__pb2.RNumber.FromString,
        )
    self.sub = channel.unary_unary(
        '/Calculator/sub',
        request_serializer=calculator__pb2.Numbers.SerializeToString,
        response_deserializer=calculator__pb2.RNumber.FromString,
        )


class CalculatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def sum(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def mult(self, request, context):
    """método de multiplicação
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def div(self, request, context):
    """método de divisão
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sub(self, request, context):
    """método de subtração
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sum': grpc.unary_unary_rpc_method_handler(
          servicer.sum,
          request_deserializer=calculator__pb2.Numbers.FromString,
          response_serializer=calculator__pb2.RNumber.SerializeToString,
      ),
      'mult': grpc.unary_unary_rpc_method_handler(
          servicer.mult,
          request_deserializer=calculator__pb2.Numbers.FromString,
          response_serializer=calculator__pb2.RNumber.SerializeToString,
      ),
      'div': grpc.unary_unary_rpc_method_handler(
          servicer.div,
          request_deserializer=calculator__pb2.Numbers.FromString,
          response_serializer=calculator__pb2.RNumber.SerializeToString,
      ),
      'sub': grpc.unary_unary_rpc_method_handler(
          servicer.sub,
          request_deserializer=calculator__pb2.Numbers.FromString,
          response_serializer=calculator__pb2.RNumber.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Calculator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
